# For Development Only
version: "3"

networks:
  traval-net:
    driver: bridge

services:
  # User microservice
  user:
    container_name: user
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - traval-net

  # Catalog microservice
  catalog:
    container_name: catalog
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - traval-net

  # Order microservice
  order:
    container_name: order
    restart: unless-stopped
    ports:
      - "5002:5002"
    networks:
      - traval-net

  # Order RabbitMQ consumer
  order-rabbitmq:
    container_name: order-rabbitmq
    restart: unless-stopped
    networks:
      - traval-net

  # Payment microservice
  payment:
    container_name: payment
    restart: unless-stopped
    ports:
      - "5003:5003"
    networks:
      - traval-net

  # Voucher microservice
  voucher:
    container_name: voucher
    restart: unless-stopped
    ports:
      - "5004:5004"
    networks:
      - traval-net
  
  # Voucher RabbitMQ consumer
  voucher-rabbitmq:
    container_name: voucher-rabbitmq
    restart: unless-stopped
    networks:
      - traval-net

  # Review microservice
  review:
    container_name: review
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      - traval-net