# For Development Only
version: "3"

networks:
  traval-net:
    driver: bridge

services:
  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.8.3-management-alpine'
    restart: unless-stopped
    ports:
      - "5672:5672" # The standard AMQP protocol port
      - "15672:15672" # HTTP management UI
    networks:
      - traval-net

  # User microservice
  user:
    container_name: user
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - traval-net

  # Catalog microservice
  catalog:
    container_name: catalog
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - traval-net

  # Order microservice
  order:
    container_name: order
    restart: unless-stopped
    ports:
      - "5002:5002"
    networks:
      - traval-net

  # Order RabbitMQ consumer
  order-rabbitmq:
    container_name: order-rabbitmq
    restart: unless-stopped
    networks:
      - traval-net
    depends_on:
      - rabbitmq

  # Payment microservice
  payment:
    container_name: payment
    restart: unless-stopped
    ports:
      - "5003:5003"
    networks:
      - traval-net

  # Voucher microservice
  voucher:
    container_name: voucher
    restart: unless-stopped
    ports:
      - "5004:5004"
    networks:
      - traval-net
  
  # Voucher RabbitMQ consumer
  voucher-rabbitmq:
    container_name: voucher-rabbitmq
    restart: unless-stopped
    networks:
      - traval-net
    depends_on:
      - rabbitmq

  # Review microservice
  review:
    container_name: review
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      - traval-net
  
  # Notification microservice
  notification:
    container_name: notification
    restart: unless-stopped
    networks:
      - traval-net
    depends_on:
      - rabbitmq