# For Development Only
version: "3"

services:
  # User microservice
  user:
    build:
      context: ./user-management
      dockerfile: Dockerfile
    command: "python /usr/src/app/user.py"
    volumes:
      - ./user-management:/usr/src/app

  # Catalog microservice
  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    command: "python /usr/src/app/catalog_item.py"
    volumes:
      - ./catalog:/usr/src/app

  # Order microservice
  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    command: "python /usr/src/app/order.py"
    volumes:
      - ./order:/usr/src/app
    
  # Payment microservice
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    command: "python /usr/src/app/payment.py"
    volumes:
      - ./payment:/usr/src/app

  # Voucher microservice
  voucher:
    build:
      context: ./voucher
      dockerfile: Dockerfile
    command: "python /usr/src/app/voucher.py"
    volumes:
      - ./voucher:/usr/src/app

  # Review microservice
  review:
    build:
      context: ./review
      dockerfile: Dockerfile
    command: "python /usr/src/app/review.py"
    volumes:
      - ./review:/usr/src/app