version: "3"

networks:
 rabbitmq-net:
  driver: bridge

services:
  # RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3.8.3-management-alpine'
    networks:
      - rabbitmq-net
    ports:
    - "5672:5672" # The standard AMQP protocol port
    - "15672:15672" # HTTP management UI