version: '3'
services:
  # Our Traval app
  app:
    container_name: app
    restart: unless-stopped
    tty: true
    networks:
      - app-net

  # Nginx
  nginx:
    container_name: nginx
    restart: unless-stopped
    tty: true
    networks:
      - app-net

# Docker Networks
networks:
  app-net:
    driver: bridge