version: '3'
services:
  # Our Traval app
  app:
    build:
      args:
        user: traval
        uid: 1000
      context: ./
      dockerfile: ./docker/app/Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # Nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/certificates