version: '3'
services:
  # Our Laravel app
  app:
    build:
      args:
        user: traval
        uid: 1000
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-net

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/certificates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net

# Docker Networks
networks:
  app-net:
    driver: bridge